spring.application.name=jobtracker

spring.datasource.url=jdbc:mysql://localhost:3306/jobtracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# google meet api
google.client.id=1336988451-a929amvm64katcojtj5bh7v0s2elqs6o.apps.googleusercontent.com
google.client.secret=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
google.refresh.token=1//04PT-rI0LmpNJCgYIARAAGAQSNwF-L9IrYFvLqT5_kYIA7mA3IQr8EvVQth_ea-T3349Ez04QvG7WUPoo6JZ2wfAm-Fd277QMut4


server.port=8081

